name = "AvifSupport"
uuid = "bff38aaf-160c-48a5-9daf-c138fff82437"
authors = ["imohag9 <souidi.hamza90@gmail.com> and contributors"]
version = "0.0.1"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
